---
title: "Getting Started with mxmmod"
author: "Kyle Husmann"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

## Outline

## A. Introduction to the Measurement Model of Derivatives (MMOD)

Describe mmod here, add formulas etc.

## B. Prepare environment

Before we begin, let's load the required libraries and the example data set.

```{r, echo=F}
library(tidyverse)
library(OpenMx)
library(mxmmod)
data("nlsy97depression")
```

Plot some example trajectories

```{r}
set.seed(1000)
subset <- sample(unique(nlsy97depression$pid), 9)

nlsy97depression %>%
  filter(pid %in% subset) %>%
  gather(measure, val, -pid, -occasion) %>%
  ggplot(aes(x=occasion, group=measure, color=measure, y=val)) +
  geom_line(position=position_jitter(w=0.1, h=0.1)) +
  facet_wrap(~pid)
```

## C. Example 1: One factor model

```{r}
structure <- list(
  F1 = c('nervous', 'down', 'depressed', 'calm', 'happy')
)
mmod_model <- mxMmodModel(data=nlsy97depression,
                          modelName='1 Factor MMOD',
                          idvar='pid', timevar='occasion', structure=structure, fiml=F)
mmod_fit <- mxRun(mmod_model)
(mmod_summary <- summary(mmod_fit))
```

```{r}
# Note: This can take a while to draw...
semPlot::semPaths(mmod_fit, 'est')
```


## D. Example 2: Two factor model

```{r}
structure2 <- list(
  F1 = c('down', 'depressed', 'happy'),
  F2 = c('nervous', 'calm')
)
mmod_model2 <- mxMmodModel(data=nlsy97depression,
                          modelName='2 Factor MMOD',
                          idvar='pid', timevar='occasion', structure=structure2)
mmod_fit2 <- mxRun(mmod_model2)
(mmod_summary2 <- summary(mmod_fit2))
```

```{r}
# Note: This can take a while to draw...
semPlot::semPaths(mmod_fit2, 'est')
```

## E. Discussion

```{r}
fits <- list(mmod_summary, mmod_summary2)

(compare_models <- tibble(
    name=map_chr(fits, 'modelName'),
    chisq=map_dbl(fits, 'Chi'),
    dof=map_dbl(fits, 'ChiDoF'),
    `-2ll`=map_dbl(fits, 'Minus2LogLikelihood'),
    aic=map_dbl(fits, 'AIC.Mx'),
    bic=map_dbl(fits, 'BIC.Mx'),
    rmsea=map_dbl(fits, 'RMSEA'),
    cfi=map_dbl(fits, 'CFI'),
    tli=map_dbl(fits, 'TLI')  
))
```

## F. Appendix: Using FIML

```{r}
structure3 <- list(
  F1 = c('nervous', 'down', 'depressed', 'calm', 'happy')
)
mmod_model3 <- mxMmodModel(data=nlsy97depression,
                          modelName='1 Factor MMOD w FIML',
                          idvar='pid', timevar='occasion', structure=structure, fiml=T)
mmod_fit3 <- mxRun(mmod_model3)
mmod_refs3 <- mxRefModels(mmod_fit3, run=T)
(mmod_summary3 <- summary(mmod_fit3, refModels=mmod_refs3))
```

